name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actonlang/setup-acton@v1
        with:
          channel: tip

      - uses: actions/checkout@v4
      
      - name: Build Project
        run: acton build

      - name: Run Tests
        run: acton test